/*
 * app_Sequence.c
 *
 *  Created on: Jan 10, 2024
 *      Author: Omare
 */
#include <stdint.h>
#include <stdbool.h>
#include "app_Sequence.h"
#include "app_DMXCore.h"

bool rb_EnableSequenceFlag = false;
bool rb_SequenceTick = false;
uint32_t rul_SeqIndex;

#define APP_SEQUENCE_PARAM_SIZE		4u

#define SEQUENCE_TOOGLE_TIME	20u
#define SEQUENCE_SHOW_TIME		50u
#define SEQUENCE_TOGGLE(channel,time) \
		{SEQ_SELECT_CH, 	channel		}, 	/* SelectCH1 */\
		{SEQ_SET_CH_DATA, 	0xFFu	}, 	/* Set Data */\
		{SEQ_SET_TIME, 		time	}, 	/* Wait Time */\
		{SEQ_TIME_WAIT, 	0u		}, 	/* Wait Time */\
		{SEQ_SELECT_CH, 	channel		}, 	/* SelectCH1 */\
		{SEQ_SET_CH_DATA, 	0x00	}, 	/* Set Data */\
		{SEQ_SET_TIME, 		time	}, 	/* Wait Time */\
		{SEQ_TIME_WAIT, 	0u		}	/* Wait Time */

#define SEQUENCE_WAIT(time)\
		{SEQ_SET_TIME, 		time	}, 	/* Wait Time */\
		{SEQ_TIME_WAIT, 	0u		} 	/* Wait Time */

#define SEQUENCE_SET_CH(channel,data)\
		{SEQ_SELECT_CH, 	channel		}, 	/* SelectCH1 */\
		{SEQ_SET_CH_DATA, 	data	} 	/* Set Data */

#define SEQUENCE_FADEUP_CH(channel,data)\
		{SEQ_SELECT_CH, 	channel		}, 	/* SelectCH */\
		{SEQ_FADEUP, 		data		}

#define SEQUENCE_FADEDOWN_CH(channel,data)\
		{SEQ_SELECT_CH, 	channel		}, 	/* SelectCH */\
		{SEQ_FADEDOWN, 		data		}

#define SEQUENCE_SET_WHITE(data)\
		SEQUENCE_SET_CH(9,data),\
		SEQUENCE_SET_CH(10,data),\
		SEQUENCE_SET_CH(11,data)

#define SEQUENCE_BULB_ON(value)\
		SEQUENCE_SET_CH(0,value),\
		SEQUENCE_SET_CH(1,value),\
		SEQUENCE_SET_CH(2,value),\
		SEQUENCE_SET_CH(3,value),\
		SEQUENCE_SET_CH(4,value),\
		SEQUENCE_SET_CH(5,value),\
		SEQUENCE_SET_CH(6,value),\
		SEQUENCE_SET_CH(7,value)

#define SEQUENCE_ALL_ON(value)\
		SEQUENCE_SET_CH(0,value),\
		SEQUENCE_SET_CH(1,value),\
		SEQUENCE_SET_CH(2,value),\
		SEQUENCE_SET_CH(3,value),\
		SEQUENCE_SET_CH(4,value),\
		SEQUENCE_SET_CH(5,value),\
		SEQUENCE_SET_CH(6,value),\
		SEQUENCE_SET_CH(7,value),\
		SEQUENCE_SET_CH(8,value),\
		SEQUENCE_SET_CH(9,value),\
		SEQUENCE_SET_CH(10,value),\
		SEQUENCE_SET_CH(11,value),\
		SEQUENCE_SET_CH(12,value)

#define COLOR_SEQ_WAIT_TIME	1
#define COLOR_SEQ_LOOP_COUNT	100
T_Sequence ColorSequence[] = {
		/* Start RED FadeUp  */
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		SEQUENCE_FADEUP_CH(0,1),
		SEQUENCE_FADEUP_CH(5,1),
		SEQUENCE_FADEUP_CH(10,1),
		SEQUENCE_FADEUP_CH(15,1),
		SEQUENCE_FADEUP_CH(20,1),
		SEQUENCE_FADEUP_CH(25,1),
		SEQUENCE_FADEUP_CH(30,1),
		SEQUENCE_FADEUP_CH(35,1),
		SEQUENCE_FADEUP_CH(40,1),
		SEQUENCE_WAIT(COLOR_SEQ_WAIT_TIME),
		{SEQ_CHECK_LOOP, 	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		SEQUENCE_FADEDOWN_CH(0,1),
		SEQUENCE_FADEDOWN_CH(5,1),
		SEQUENCE_FADEDOWN_CH(10,1),
		SEQUENCE_FADEDOWN_CH(15,1),
		SEQUENCE_FADEDOWN_CH(20,1),
		SEQUENCE_FADEDOWN_CH(25,1),
		SEQUENCE_FADEDOWN_CH(30,1),
		SEQUENCE_FADEDOWN_CH(35,1),
		SEQUENCE_FADEDOWN_CH(40,1),
		SEQUENCE_WAIT(COLOR_SEQ_WAIT_TIME),
		{SEQ_CHECK_LOOP, 	0u		},

		{SEQ_JUMP, 			0u		},	/* Start Over Again */

		/* Start BLUE FadeDown  */
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		{SEQ_SELECT_CH, 	11u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	14u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	17u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	20u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	23u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SET_TIME,		COLOR_SEQ_WAIT_TIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},

		/* Start GREEN FadeUp  */
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		{SEQ_SELECT_CH, 	10u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	13u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	16u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	19u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	22u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	25u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SET_TIME,		COLOR_SEQ_WAIT_TIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},

		/* Start RED FadeDown  */
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		{SEQ_SELECT_CH, 	0u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	1u		},
		{SEQ_FADEDOWN, 		3u		},
		{SEQ_SELECT_CH, 	2u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	3u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	4u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	5u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	6u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	7u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	9u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	12u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	15u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	18u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	21u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	24u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SET_TIME,		COLOR_SEQ_WAIT_TIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},

		/* Start BLUE FadeUp  */
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		{SEQ_SELECT_CH, 	11u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	14u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	17u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	20u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SELECT_CH, 	23u		},
		{SEQ_FADEUP, 		1u		},
		{SEQ_SET_TIME,		COLOR_SEQ_WAIT_TIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},

		/* Start GREEN FadeDown  */
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	COLOR_SEQ_LOOP_COUNT	},
		{SEQ_SELECT_CH, 	10u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	13u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	16u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	19u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	22u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SELECT_CH, 	25u		},
		{SEQ_FADEDOWN, 		1u		},
		{SEQ_SET_TIME,		COLOR_SEQ_WAIT_TIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},

		{SEQ_JUMP, 			0u		}	/* Start Over Again */
};

#define SEQ_MAIN_WAITTIME	100
#define SEQ_MAIN_FADE_STEP	1

/* AC Sequence Config */
#define ACCONTROL_DMX_START_CHANNEL 0
#define SEQ_AC_START_CHANNEL	(ACCONTROL_DMX_START_CHANNEL - 1u)
#define SEQ_AC_CHANNEL_INCREASE	(3u)
#define SEQ_AC_NEXT_CHANNEL_A(idx)	(SEQ_AC_START_CHANNEL + (0u) + (idx*SEQ_AC_CHANNEL_INCREASE))
#define SEQ_AC_NEXT_CHANNEL_B(idx)	(SEQ_AC_START_CHANNEL + (1u) + (idx*SEQ_AC_CHANNEL_INCREASE))
#define SEQ_AC_NEXT_CHANNEL_C(idx)	(SEQ_AC_START_CHANNEL + (2u) + (idx*SEQ_AC_CHANNEL_INCREASE))
#define SEQ_AC_NEXT_CHANNEL_D(idx)	(SEQ_AC_START_CHANNEL + (3u) + (idx*SEQ_AC_CHANNEL_INCREASE))

/* DC Sequence Config */
#define PWM_DMX_START_CHANNEL 1
#define SEQ_DC_START_CHANNEL	(PWM_DMX_START_CHANNEL - 1u)
#define SEQ_DC_CHANNEL_INCREASE	(4u)
#define SEQ_DC_NEXT_CHANNEL_A(idx)	(SEQ_DC_START_CHANNEL + (0u) + (idx*SEQ_DC_CHANNEL_INCREASE))
#define SEQ_DC_NEXT_CHANNEL_B(idx)	(SEQ_DC_START_CHANNEL + (1u) + (idx*SEQ_DC_CHANNEL_INCREASE))
#define SEQ_DC_NEXT_CHANNEL_C(idx)	(SEQ_DC_START_CHANNEL + (2u) + (idx*SEQ_DC_CHANNEL_INCREASE))
#define SEQ_DC_NEXT_CHANNEL_D(idx)	(SEQ_DC_START_CHANNEL + (3u) + (idx*SEQ_DC_CHANNEL_INCREASE))

T_Sequence RainbowSequence[] = {
/****************************************/
		{SEQ_INIT_FRAME,	0u		},
		{SEQ_INIT_LOOP, 	100u	},
		/*AC*/
#if(SEQ_AC_NEXT_CHANNEL_A(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_A(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_A(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_A(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(3) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_A(3),SEQ_MAIN_FADE_STEP),
#endif

		/*DC*/
#if(SEQ_DC_NEXT_CHANNEL_A(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_A(6),SEQ_MAIN_FADE_STEP),
#endif


#if(SEQ_DC_NEXT_CHANNEL_D(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_D(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_D(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_D(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_D(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_D(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(5),SEQ_MAIN_FADE_STEP),
#endif

		{SEQ_SET_TIME,		SEQ_MAIN_WAITTIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},
/****************************************/
/****************************************/
		{SEQ_INIT_LOOP, 	100u	},
		/*AC*/
#if(SEQ_AC_NEXT_CHANNEL_B(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_B(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_B(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_B(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(3) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_B(3),SEQ_MAIN_FADE_STEP),
#endif
		/*DC*/
#if(SEQ_DC_NEXT_CHANNEL_B(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_B(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(6),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_AC_NEXT_CHANNEL_A(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_A(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_A(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_A(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_A(3) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_A(3),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_DC_NEXT_CHANNEL_A(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_A(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_A(6),SEQ_MAIN_FADE_STEP),
#endif

		{SEQ_SET_TIME,		SEQ_MAIN_WAITTIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},
/****************************************/
/****************************************/
		{SEQ_INIT_LOOP, 	100u	},

#if(SEQ_AC_NEXT_CHANNEL_C(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_C(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_C(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_C(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_C(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_C(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_C(3) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_AC_NEXT_CHANNEL_C(3),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_DC_NEXT_CHANNEL_C(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_C(6),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_AC_NEXT_CHANNEL_B(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_B(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_B(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_B(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_B(3) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_B(3),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_DC_NEXT_CHANNEL_B(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_B(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_B(6),SEQ_MAIN_FADE_STEP),
#endif

		{SEQ_SET_TIME,		SEQ_MAIN_WAITTIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},
/****************************************/
/****************************************/
		{SEQ_INIT_LOOP, 	100u	},

#if(SEQ_DC_NEXT_CHANNEL_D(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_D(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEUP_CH(SEQ_DC_NEXT_CHANNEL_D(5),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_AC_NEXT_CHANNEL_C(0) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_C(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_C(1) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_C(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_AC_NEXT_CHANNEL_C(2) < (SEQ_AC_START_CHANNEL + ACCONTROL_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_AC_NEXT_CHANNEL_C(2),SEQ_MAIN_FADE_STEP),
#endif

#if(SEQ_DC_NEXT_CHANNEL_C(0) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(0),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(1) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(1),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(2) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(2),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(3) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(3),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(4) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(4),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(5) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(5),SEQ_MAIN_FADE_STEP),
#endif
#if(SEQ_DC_NEXT_CHANNEL_C(6) < (SEQ_DC_START_CHANNEL + PWM_N_CHANNELS))
		SEQUENCE_FADEDOWN_CH(SEQ_DC_NEXT_CHANNEL_C(6),SEQ_MAIN_FADE_STEP),
#endif

		{SEQ_SET_TIME,		SEQ_MAIN_WAITTIME	},
		{SEQ_TIME_WAIT,		0u		},
		{SEQ_CHECK_LOOP, 	0u		},
/****************************************/
/****************************************/
		{SEQ_JUMP, 			0u		}	/* Start Over Again */
};

void HAL_TIM_PeriodElapsedCallback(TIM_HandleTypeDef *htim)
{
  /* Prevent unused argument(s) compilation warning */
  UNUSED(htim);

  rb_EnableSequenceFlag = true;
  rb_SequenceTick = true;

}


void app_Sequence_Main(void)
{
	if((false != rb_EnableSequenceFlag) &&
			(false != rb_SequenceTick))
	{
		rb_SequenceTick = false;
		app_SequenceCommandExec(ColorSequence);

	}
	else
	{
		/* Do Nothing */
	}
}


void app_SequenceCommandExec(T_Sequence* l_Sequence)
{
	bool l_ExecFlag;
	static unsigned char lub_CHIndex;
	static unsigned int lul_SeqStep = 0u;
	static uint32_t lul_TimeCounter = 0u;
	static uint32_t lul_LoopCounter = 0u;
	static uint32_t lul_FirstLoopStep = 0u;

	l_ExecFlag = true;
	do
	{
		switch(l_Sequence[lul_SeqStep].cmd)
		{
		case SEQ_INIT_FRAME:
		{
			l_ExecFlag = true;
			lul_SeqStep++;
		}break;
		case SEQ_END_FRAME:
		{
			l_ExecFlag = false;
			lul_SeqStep++;
		}break;
		case SEQ_SELECT_CH:
		{
			lub_CHIndex = (uint8_t)l_Sequence[lul_SeqStep].param;
			lul_SeqStep++;
		}break;
		case SEQ_SET_CH_DATA:
		{
			DMX_Channels[lub_CHIndex] = (uint8_t)l_Sequence[lul_SeqStep].param;
			lul_SeqStep++;
		}break;
		case SEQ_SET_TIME:
		{
			lul_TimeCounter = l_Sequence[lul_SeqStep].param;
			lul_SeqStep++;
		}break;
		case SEQ_TIME_WAIT:
		{
			if(lul_TimeCounter > 0u)
			{
				lul_TimeCounter--;
				l_ExecFlag=false;
			}
			else
			{
				lul_SeqStep++;
			}
		}break;
		case SEQ_JUMP:
		{
			lul_SeqStep = l_Sequence[lul_SeqStep].param;
		}break;
		case SEQ_FADEUP:
		{
			if(DMX_Channels[lub_CHIndex] < PWM_BASECNTR_MAX)
			{
				if((PWM_BASECNTR_MAX - DMX_Channels[lub_CHIndex]) >= l_Sequence[lul_SeqStep].param)
				{
					DMX_Channels[lub_CHIndex] += (uint8_t)l_Sequence[lul_SeqStep].param;
				}
				else
				{
					DMX_Channels[lub_CHIndex] = PWM_BASECNTR_MAX;
				}
			}
			lul_SeqStep++;
		}break;
		case SEQ_FADEDOWN:
		{
			if(DMX_Channels[lub_CHIndex] > PWM_BASECNTR_MIN)
			{
				if((DMX_Channels[lub_CHIndex] - PWM_BASECNTR_MIN) >= l_Sequence[lul_SeqStep].param)
				{
					DMX_Channels[lub_CHIndex] -= (uint8_t)l_Sequence[lul_SeqStep].param;
				}
				else
				{
					DMX_Channels[lub_CHIndex] = PWM_BASECNTR_MIN;
				}
			}
			lul_SeqStep++;
		}break;
		case SEQ_INIT_LOOP:
		{
			lul_LoopCounter = l_Sequence[lul_SeqStep].param;
			lul_SeqStep++;
			lul_FirstLoopStep = lul_SeqStep;
		}break;
		case SEQ_CHECK_LOOP:
		{
			if(lul_LoopCounter > 0u)
			{
				lul_LoopCounter--;
				lul_SeqStep = lul_FirstLoopStep;
			}
			else
			{
				lul_SeqStep++;
			}
		}break;
		default:
		{
			l_ExecFlag = false;
			lul_SeqStep = 0u;
		}break;
		}
	}while(l_ExecFlag);
}
